image: python:latest
before_script:
  - python --version
  - pip install sphinx
  - pip install numpy
  - pip install obspy
  - pip install get_mseed_data
  
stages:
  - alldoc
pages:
  stage: alldoc
  script:
    - pwd
    - ls ./
    - cd docs
    - make html
    - cd ..
    - mv docs/build/html public/
  artifacts:
    paths:
      - public
  only:
    - master
